title: Bosong Qi's Homepage
page-top-title: Bosong Qi
top-section-bg-text: Action is the Foundational Key to All Success
home-subtitle: Bosong Qi&ensp;|&ensp;齐泊淞
copyright-text: '&copy; Bosong Qi 2023-2025. All Rights Reserved.'
